title: Aidana Moldabayeva
email: aidana.moldabayeva@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I am Aidana, an amateur photographer and traveller passionate
  about cycling to different locations, making beautiful photos and
  reading as many books as I can.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iamaidana.github.io" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: iamaidana
github_username:  iamaidana
repository: "iamaidana/iamaidana.github.io"

show_downloads: true
google_analytics: [Your Google Analytics tracking ID]


# Build settings
theme: 
plugins:
  - jekyll-feed
  - jekyll-target-blank

# Exclude from processing.
# social
author: by Aidana
image: 
instagram:
  username: iamaidana

target-blank:
    rel: nofollow

header_page_refs: ['about', 'books', 'photos', 'resume', 'contact']



# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
